# Generated by Django 5.2.4 on 2025-07-16 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_tour_description_tour_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tourtype',
            name='country',
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='', max_length=1020, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='img', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='имейл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.car', verbose_name='машина'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=20, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='', verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='тур'),
        ),
        migrations.AlterField(
            model_name='car',
            name='air_codinting',
            field=models.BooleanField(default=False, verbose_name='кондей'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_style',
            field=models.CharField(default='sedan', max_length=50, verbose_name='стили'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='год'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.tour', verbose_name='туры'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='балл'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=30, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(verbose_name='конец'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='group_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourgroupdetail', verbose_name='детали группы'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='themes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourthemes', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourtype', verbose_name='тип тура'),
        ),
        migrations.AlterField(
            model_name='tourgroupdetail',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tourgroupdetail',
            name='group_size',
            field=models.CharField(max_length=50, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='tourthemes',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tourthemes',
            name='group_themes',
            field=models.CharField(max_length=100, verbose_name='темы'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='with_gid',
            field=models.BooleanField(verbose_name='с гидом'),
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_img', to='tour.car', verbose_name='машина')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='область')),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.country')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tour.region', verbose_name='регион'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
