# Generated by Django 5.2.4 on 2025-07-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_country_remove_booking_second_name_remove_image_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='описание'),
        ),
    ]
